export const artisansAssets = {
  sculpture: "/images/artisans/sculpture.jpg",
  gallery: "/images/artisans/gallery.jpg",
  portrait: "/images/artisans/portrait.jpg",
  sunset: "/images/artisans/sunset.jpg",
  heroVideo: "/images/artisans/hero-poster.jpg",
  heroVideoSrc: "/videos/artisans-hero.mp4?v=1080",
  video: "/images/artisans/video-poster.jpg",
  videoSrc: "/videos/artisans-video-band.mp4?v=1080",
  cta: "/images/artisans/cta.jpg",
  team: {
    carlos: "/images/artisans/team-1.jpg",
    andre: "/images/artisans/team-2.jpg",
    vitor: "/images/artisans/team-3.jpg",
    jessica: "/images/artisans/team-4.jpg",
    anabela: "/images/artisans/team-5.jpg",
    ana: "/images/artisans/team-6.jpg",
    margarida: "/images/artisans/team-7.jpg",
  },
} as const;
